# Codecov configuration
# See https://docs.codecov.io/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 70%          # Project must maintain 70% coverage
        threshold: 5%        # Allow 5% drop before failing
    patch:
      default:
        target: 70%          # New code must have 70% coverage

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/mocks/**"
  - "cmd/*/main.go"        # Entry points don't need test coverage
