# GitGuardian configuration for ggshield CLI and GitHub App
# Place in repository root to ignore test tokens and prevent false positives

# IMPORTANT: Only scan new commits, not entire git history
# This prevents blocking PRs due to historical secrets that have already been rotated
#
# Historical Context (from ERROR_LOG.md):
# - Secrets existed in commits prior to November 2025
# - All secrets were rotated and removed in commit 65859f8
# - Future commits should not contain secrets (pre-commit hook enforces this)
# - GitGuardian should only flag NEW secret introductions, not old ones
#
# Configuration Strategy:
# 1. Use ignored_detectors to skip generic high-entropy patterns
# 2. Use ignored_paths to skip test files
# 3. GitHub App should be configured to "Check only new commits" in repository settings
version: 2

secret:
  # Ignore specific test tokens by exact value
  ignored_matches:
    # Test GitHub tokens used in unit tests (internal/session/redis_store_test.go)
    - name: test_github_token_1
      match: gho_test123
    
    - name: test_github_token_2
      match: gho_test456
    
    # Test JWT secret used in portal tests
    - name: test_jwt_secret
      match: test-secret-key
    
    # Test client credentials
    - name: test_client_id
      match: test-client-id
    
    - name: test_client_secret
      match: test-client-secret

  # Exclude test directories and test files from scanning
  ignored_paths:
    - 'tests/**'
    - '**/*_test.go'
    - '**/*.test.ts'
    - '**/*.spec.ts'
    - 'test-*.js'
    - 'test-*.html'
    - 'test-results/**'
    - '**/testdata/**'

  # Ignore historical commits with secrets (already rotated, no security risk)
  # These secrets were removed and rotated in commit 65859f8 (2025-11)
  ignored_detectors:
    - Generic High Entropy Secret
    - JWT
    - GitHub Token

# Exit with non-zero code on real secret detections
exit_zero: false

# Enable verbose output for debugging (optional)
verbose: false
