# GitGuardian configuration for ggshield CLI
# Place in repository root to ignore test tokens and prevent false positives

secret:
  # Ignore specific test tokens by exact value
  ignored_matches:
    # Test GitHub tokens used in unit tests (internal/session/redis_store_test.go)
    - name: test_github_token_1
      match: gho_test123
    
    - name: test_github_token_2
      match: gho_test456
    
    # Test JWT secret used in portal tests
    - name: test_jwt_secret
      match: test-secret-key
    
    # Test client credentials
    - name: test_client_id
      match: test-client-id
    
    - name: test_client_secret
      match: test-client-secret

  # Exclude test directories and test files from scanning
  ignored_paths:
    - 'tests/**'
    - '**/*_test.go'
    - '**/*.test.ts'
    - '**/*.spec.ts'
    - 'test-*.js'
    - 'test-*.html'
    - 'test-results/**'
    - '**/testdata/**'

# Exit with non-zero code on real secret detections
exit_zero: false

# Enable verbose output for debugging (optional)
verbose: false
