# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Check for misspelled English words
    - revive        # Replacement for golint
    - gocritic      # Opinionated linter
    - gosec         # Security issues
    - bodyclose     # Check HTTP response body closed
    - nilerr        # Find code returning nil even if err != nil

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G404 # Weak random number generator (OK for non-crypto use)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - errcheck
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
