name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Report bugs or unexpected behavior. Please provide as much detail as possible.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: One-line summary of the bug
      placeholder: "Login button does not redirect to GitHub OAuth"
    validations:
      required: true

  - type: dropdown
    id: app
    attributes:
      label: Which app is affected?
      options:
        - Portal
        - Review
        - Logs
        - Analytics
        - Build
        - Multiple/Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: What is happening vs. what should happen?
      placeholder: |
        When I click the "Login with GitHub" button, nothing happens.
        Expected: Should redirect to GitHub OAuth authorization page.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Navigate to http://localhost:3000
        2. Click "Login with GitHub" button
        3. Observe that nothing happens
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Should redirect to GitHub OAuth page"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Button click has no effect"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages from console or logs?
      placeholder: |
        Browser console:
        Uncaught TypeError: Cannot read property 'href' of undefined
          at handleLogin (Login.jsx:45)
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      value: |
        - OS:
        - Browser:
        - Node Version:
        - Python Version:
        - Docker:
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (app unusable)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, related issues, or other context
      placeholder: |
        This started happening after PR #42 was merged.
        Screenshot attached.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have provided steps to reproduce
          required: true
        - label: I have included error logs (if applicable)
          required: false
