// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
// GREEN PHASE: Minimal Templ for session creation form

package review_templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

func SessionForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"review-session-form\" class=\"flex flex-col gap-4 max-w-md mx-auto p-4 bg-white rounded shadow\" aria-label=\"Create Review Session\" autocomplete=\"off\" role=\"form\"><label for=\"pasted_code\" class=\"font-semibold\">Paste code</label> <textarea id=\"pasted_code\" name=\"pasted_code\" class=\"textarea textarea-bordered\" required aria-required=\"true\" aria-label=\"Paste code\" rows=\"6\"></textarea> <label for=\"github_url\" class=\"font-semibold\">or GitHub URL</label> <input id=\"github_url\" name=\"github_url\" class=\"input input-bordered\" type=\"url\" aria-label=\"GitHub URL\" placeholder=\"https://github.com/user/repo\"> <label for=\"file-upload\" class=\"font-semibold\">or Upload file</label> <input id=\"file-upload\" name=\"file\" class=\"file-input file-input-bordered\" type=\"file\" aria-label=\"Upload file\" accept=\".go,.py,.js,.ts,.java,.cpp,.c,.rb,.cs,.php,.txt\"><div class=\"error-message text-error\" aria-live=\"polite\"></div><button type=\"submit\" class=\"btn btn-primary\" aria-label=\"Start Review\">Start Review</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
