apiVersion: v1
kind: Application
metadata:
  name: go-htmx-starter
  description: Minimal Go + HTMX starter template with platform contract enforcement
  version: 1.0.0
  
spec:
  # Application type
  type: web
  
  # Runtime
  runtime:
    language: go
    version: "1.22"
  
  # Service configuration
  service:
    port: 8080
    healthCheck:
      path: /health
      interval: 30s
      timeout: 3s
      retries: 3
  
  # Environment variables
  env:
    - name: PORT
      value: "8080"
    - name: SERVICE_NAME
      value: go-htmx-starter
    - name: LOG_LEVEL
      value: INFO
  
  # Resources
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 50m
  
  # Container configuration
  container:
    image: go-htmx-starter:latest
    user: 1000:1000  # Non-root user
    
  # Platform contract
  contract:
    health:
      enabled: true
      endpoint: /health
    logging:
      structured: true
      format: json
      correlation: true
    headers:
      correlation: X-Correlation-ID
