// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
// Package templates provides Templ components for the Logs service UI.

package logs_templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templruntime "github.com/a-h/templ/runtime"
)

// Dashboard renders the main logs dashboard page with real-time log streaming,
// filtering, and virtual scrolling support.
// Features: WebSocket streaming, expandable details, date filtering, search debouncing,
// toast notifications, copy-to-clipboard, responsive design, and accessibility (WCAG 2.1 AA).
func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"logs-container\"><header class=\"logs-header\"><h1>📝 DevSmith Logs</h1><p class=\"subtitle\">Real-time development logs</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Filters().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = Controls().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</header><main class=\"logs-main\"><!-- Toast notification container for error/warning/success messages --><div id=\"toast-container\" class=\"toast-container\"></div><!-- Log output area with virtual scrolling support --><div id=\"logs-output\" class=\"logs-output\" role=\"list\"></div><div id=\"logs-loading\" class=\"loading\">Connecting to log stream...</div></main></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Logs Dashboard").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Filters renders the filter controls for level, service, date range, and search.
// Supports real-time filtering with debounced search input.
func Filters() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"filters\"><!-- Log level filter dropdown --><div class=\"filter-group\"><label for=\"level-filter\">Level:</label> <select id=\"level-filter\" aria-label=\"Filter logs by level\"><option value=\"all\">All Levels</option> <option value=\"info\">INFO</option> <option value=\"warn\">WARN</option> <option value=\"error\">ERROR</option></select></div><!-- Service filter dropdown --><div class=\"filter-group\"><label for=\"service-filter\">Service:</label> <select id=\"service-filter\" aria-label=\"Filter logs by service\"><option value=\"all\">All Services</option> <option value=\"portal\">Portal</option> <option value=\"review\">Review</option> <option value=\"logs\">Logs</option> <option value=\"analytics\">Analytics</option></select></div><!-- Date range picker: from date --><div class=\"filter-group\"><label for=\"date-from\">From:</label> <input type=\"date\" id=\"date-from\" data-date-from aria-label=\"Filter logs from date\"></div><!-- Date range picker: to date --><div class=\"filter-group\"><label for=\"date-to\">To:</label> <input type=\"date\" id=\"date-to\" data-date-to aria-label=\"Filter logs to date\"></div><!-- Search input with 300ms debounce --><div class=\"filter-group\"><label for=\"search-input\">Search:</label> <input type=\"text\" id=\"search-input\" placeholder=\"Filter by message...\" aria-label=\"Search logs by message\"></div><!-- Apply filters button (mainly for date range updates) --><button id=\"apply-filters\" class=\"btn-control\" aria-label=\"Apply date filters\">Apply Filters</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// Controls renders the dashboard control buttons for pause, auto-scroll, clear, and status.
func Controls() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"controls\"><!-- Pause/resume streaming button --><button id=\"pause-btn\" class=\"btn-control\" title=\"Pause streaming\" aria-label=\"Pause log streaming\">⏸️ Pause</button><!-- Auto-scroll toggle button --><button id=\"auto-scroll-btn\" class=\"btn-control active\" title=\"Auto-scroll\" aria-label=\"Toggle auto-scroll\">📜 Auto-scroll</button><!-- Clear all logs button --><button id=\"clear-btn\" class=\"btn-control\" title=\"Clear logs\" aria-label=\"Clear all logs\">🗑️ Clear</button><!-- WebSocket connection status indicator (live region) --><span id=\"connection-status\" class=\"status-indicator\" role=\"status\" aria-live=\"polite\">🟢 Connected</span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
